name: CI - Maven Build & Test

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

# Cần quyền ghi để submit dependency graph (fix lỗi 403)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      # Build + unit test
      - name: Maven verify
        run: ./mvnw -B -ntp clean verify

      # Lưu test reports & jar (nếu cần debug)
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*.xml
            **/target/failsafe-reports/*.xml
          if-no-files-found: ignore

      - name: Upload built jars
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            **/target/*.jar
          if-no-files-found: ignore

      # Submit dependency graph (cần permissions: contents: write)
      - name: Submit dependencies
        uses: advanced-security/maven-dependency-submission-action@v5
        # mặc định dùng ${{ github.token }}
